topic_vocabularies = {
    "Study 📚": ["academic", "coursework", "research", "thesis", "dissertation", "curriculum", "tutor", "lecture", "seminar", "assignment"],
    "Work 💼": ["career", "profession", "occupation", "job", "employment", "colleague", "supervisor", "promotion", "salary", "benefits"],
    "Hometown 🏡": ["native", "local", "community", "neighborhood", "heritage", "landmark", "countryside", "population", "culture", "tradition"],
    "Home/ Accommodation 🏘️": ["apartment", "residence", "landlord", "tenant", "rent", "lease", "furnish", "amenities", "utilities", "mortgage"],
    "Family 👨‍👩‍👧‍👦": ["relative", "sibling", "spouse", "parent", "grandparent", "cousin", "nephew", "niece", "in-law", "extended"],
    "Friends 👥": ["companion", "acquaintance", "classmate", "roommate", "bestie", "hangout", "gathering", "support", "trust", "loyalty"],
    "Clothes 👕": ["attire", "garment", "outfit", "apparel", "fashion", "style", "wardrobe", "fabric", "pattern", "accessories"],
    "Fashion 👗": ["trend", "designer", "brand", "collection", "runway", "model", "accessories", "haute couture", "prêt-à-porter", "vintage"],
    "Gifts 🎁": ["present", "surprise", "souvenir", "token", "wrapping", "occasion", "thoughtful", "generous", "appreciate", "gratitude"],
    "Daily routine 📅": ["habit", "schedule", "chore", "task", "errand", "routine", "lifestyle", "productivity", "time management", "discipline"],
    "Daily activities 🏃‍♂️": ["exercise", "hobby", "leisure", "pastime", "entertainment", "recreation", "relaxation", "self-care", "productivity", "balance"],
    "Food/ Cooking 🍳": ["cuisine", "recipe", "ingredient", "dish", "meal", "snack", "appetizer", "culinary", "gourmet", "nutrition"],
    "Drinks 🥤": ["beverage", "refreshment", "cocktail", "smoothie", "milkshake", "juice", "soda", "tea", "coffee", "mocktail"],
    "Going out 🎉": ["socialize", "party", "clubbing", "cinema", "restaurant", "cafe", "outing", "entertainment", "nightlife", "adventure"],
    "Hobbies 🎨": ["interest", "passion", "craft", "collection", "activity", "skill", "talent", "creativity", "enthusiasm", "dedication"],
    "Language 🌐": ["fluency", "bilingual", "dialect", "accent", "vocabulary", "grammar", "pronunciation", "communication", "expression", "comprehension"],
    "Leisure time activity ⏰": ["relaxation", "entertainment", "recreation", "hobby", "pastime", "enjoyment", "fun", "pleasure", "indulgence", "break"],
    "Sports ⚽": ["athlete", "competition", "tournament", "training", "fitness", "team", "coach", "championship", "sportsmanship", "dedication"],
    "Future plan 🔮": ["aspiration", "goal", "ambition", "career", "education", "dream", "target", "motivation", "strategy", "success"],
    "Music 🎵": ["melody", "rhythm", "genre", "instrument", "concert", "album", "lyrics", "composer", "artist", "band"],
    "Newspapers 📰": ["headline", "article", "journalist", "editor", "column", "advertisement", "circulation", "tabloid", "broadsheet", "editorial"],
    "Pets 🐾": ["companion", "furry", "breed", "adoption", "veterinarian", "grooming", "obedience", "training", "affection", "responsibility"],
    "Flowers & Plants 🌸": ["bouquet", "garden", "floral", "botanical", "greenhouse", "nursery", "landscaping", "horticulture", "cultivation", "irrigation"],
    "Reading 📖": ["novel", "fiction", "biography", "literature", "author", "publisher", "bookstore", "library", "genre", "bestseller"],
    "Dancing 💃": ["choreography", "performance", "rhythm", "style", "movement", "balance", "grace", "expression", "technique", "improvisation"],
    "Exercise 💪": ["fitness", "workout", "training", "cardio", "strength", "endurance", "stamina", "flexibility", "balance", "coordination"],
    "Shopping 🛍️": ["retail", "bargain", "discount", "brand", "mall", "boutique", "online", "consumer", "purchase", "budget"],
    "Magazines & TV 📺": ["publication", "edition", "subscription", "channel", "program", "series", "episode", "reality show", "documentary", "sitcom"],
    "Travelling ✈️": ["journey", "destination", "tourist", "explore", "adventure", "sightseeing", "souvenir", "itinerary", "accommodation", "transportation"],
    "Interesting places 🏰": ["landmark", "attraction", "museum", "gallery", "architecture", "heritage", "scenic", "historical", "cultural", "natural wonder"],
    "Bicycle 🚲": ["cycling", "ride", "pedal", "brake", "helmet", "trail", "mountain", "road", "commute", "exercise"],
    "Seasons 🍂": ["spring", "summer", "autumn", "winter", "weather", "climate", "temperature", "equinox", "solstice", "transition"],
    "Maps 🗺️": ["navigation", "direction", "route", "location", "landmark", "scale", "compass", "GPS", "cartography", "topography"],
    "Internet & Technology 💻": ["online", "digital", "device", "software", "network", "browser", "app", "social media", "cybersecurity", "innovation"],
    "Weather ☀️": ["forecast", "temperature", "climate", "humidity", "precipitation", "storm", "breeze", "meteorology", "atmosphere", "seasonal"],
    "Festivals 🎆": ["celebration", "tradition", "custom", "holiday", "carnival", "parade", "fireworks", "cultural", "religious", "community"],
    "Culture/ Tradition 🎭": ["heritage", "custom", "belief", "value", "norm", "diversity", "identity", "ethnicity", "ritual", "folklore"]
}